# api.py
import sys
import re
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import json
import csv
import os
from rdflib import Graph
from dotenv import load_dotenv

load_dotenv()

VPS_IP = os.getenv("VPS_IP")

# Add rag-lab to path so we can import your script
sys.path.append('./rag-lab')
from master_chat import LoL_RAG_System

app = FastAPI()

# Allow your Next.js app to talk to this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize your KG and KGE models once when the server starts
print("Starting up FastAPI and loading Knowledge Graph...")
rag_system = LoL_RAG_System()

class ChatRequest(BaseModel):
    message: str

@app.post("/api/chat")
async def chat_endpoint(request: ChatRequest):
    user_q = request.message
    
    # 1. Generate SPARQL and fetch facts
    query, facts = rag_system.get_sparql_context(user_q,env="groq")
    
    # 2. Build the context (using your exact fallback logic)
    if facts:
        context = "DATABASE FACTS:\n" + "\n".join(facts)
    else:
        match = re.search(r"([A-Z][a-z]+)", user_q)
        name = match.group(1) if match else "Aatrox"
        context = f"NO DATA FOUND. KGE PREDICTIONS FOR {name}:\n" + rag_system.get_kge_prediction(name)
        
    # 3. Prompt the LLM
    final_prompt = f"""You are a League of Legends data bot.
    I have queried the database for you. 
    QUERY USED: {query}
    RESULTS FOUND: {context}
    USER QUESTION: {user_q}
    INSTRUCTION: Use the RESULTS FOUND to answer the QUESTION. 
    The variable names in the results (like 'val' or 'desc') correspond to what you asked for in the query.
    If the answer is there, state it clearly. If not, say you don't know.
    ANSWER:"""
    
    answer = rag_system.ask_groq(final_prompt)
    
    # 4. Return data to Next.js
    return {
        "content": answer,
        "sparql": query if query else "No SPARQL query generated."
    }
    
@app.get("/api/champions")
async def get_all_champions():
    """Reads the entire enriched.json file generated by the pipeline."""
    file_path = "data/processed/enriched.json"
    if not os.path.exists(file_path):
        return []
        
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        champions_list = []
        
        for champ in data:
            
            roles = champ.get("roles", [])
            role_str = ", ".join(roles) if isinstance(roles, list) else str(roles)
            
            regions = champ.get("regions", ["Unknown"])
            region_str = ", ".join(regions) if isinstance(regions, list) else str(regions)
            
            # ADDITION: Grab the lore, spells, and stats!
            champions_list.append({
                "name": champ.get("name", "Unknown"),
                "title": champ.get("title", ""),
                "role": role_str or "Unknown",
                "region": region_str,
                "lore": champ.get("lore", "No lore available."),
                "spells": [{"id": s.get("id"), "name": s.get("name"), "description": s.get("description"), "cooldown_burn": s.get("cooldown_burn")} for s in champ.get("abilities", [])],
                "stats": champ.get("stats", {})
            })
            
        return champions_list
    except Exception as e:
        print(f"Error reading champions: {e}")
        return []

@app.get("/api/alignments")
async def get_all_alignments():
    """Reads the alignment_mapping.csv file to show Wikidata connections."""
    file_path = "data/processed/alignment_mapping.csv"
    if not os.path.exists(file_path):
        return []
        
    try:
        alignments = []
        with open(file_path, "r", encoding="utf-8") as f:
            # Assuming CSV has headers like: source, property, target
            reader = csv.reader(f)
            headers = next(reader, None) # Skip header
            for row in reader:
                if len(row) >= 3:
                    alignments.append({
                        "entity": row[0],
                        "wdProperty": row[1],
                        "wdTarget": row[2]
                    })
        return alignments
    except Exception as e:
        print(f"Error reading alignments: {e}")
        return []

@app.get("/api/schema")
async def get_full_schema():
    """Parses the lol_ontology_v3.ttl file to return the exact graph schema."""
    file_path = "lol_ontology_v3.ttl"
    if not os.path.exists(file_path):
        return []

    try:
        g = Graph()
        g.parse(file_path, format="turtle")

        # SPARQL query to fetch all properties, their types, domains, and ranges
        q = """
        PREFIX owl: <http://www.w3.org/2002/07/owl#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        
        SELECT ?prop ?type ?domain ?range WHERE {
          ?prop a ?type .
          FILTER (?type IN (owl:ObjectProperty, owl:DatatypeProperty))
          OPTIONAL { ?prop rdfs:domain ?domain }
          OPTIONAL { ?prop rdfs:range ?range }
        }
        """
        
        schema_list = []
        for row in g.query(q):
            prop_uri = str(row.prop)
            
            # Clean up URIs to look nice in the frontend (e.g., lol:championName)
            name = prop_uri.split("#")[-1] if "#" in prop_uri else prop_uri.split("/")[-1]
            prefix = "lol:" if "leagueoflegends" in prop_uri else "wd:"
            
            prop_type = "ObjectProperty" if "ObjectProperty" in str(row.type) else "DatatypeProperty"
            
            # Clean up domains and ranges
            domain = str(row.domain).split("#")[-1] if row.domain else "Any"
            range_val = str(row.range).split("#")[-1] if row.range else "Any"
            
            # Simplify standard XSD types
            if "XMLSchema" in range_val:
                range_val = f"xsd:{range_val.split('XMLSchema')[-1]}"

            schema_list.append({
                "prefix": prefix,
                "name": name,
                "type": prop_type,
                "domain": domain,
                "range": range_val
            })
            
        # Sort alphabetically by property name
        return sorted(schema_list, key=lambda x: x["name"])

    except Exception as e:
        print(f"Error reading schema: {e}")
        return []

@app.get("/api/alignments")
async def get_all_alignments():
    """Reads the alignment_mapping.csv file and formats it for the frontend."""
    file_path = "data/processed/alignment_mapping.csv"
    if not os.path.exists(file_path):
        return []
        
    try:
        alignments = []
        with open(file_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            
            for row in reader:
                # 1. Grab raw values safely using the exact CSV headers
                raw_source = row.get("Private Entity", "")
                raw_target = row.get("External URI", "")
                raw_conf = row.get("Confidence", "0.0")
                raw_label = row.get("Label", "")
                
                # 2. Clean up Source (e.g., "http://.../Aatrox" -> "lol:Aatrox")
                source = raw_source.replace("http://leagueoflegends.knowledge/champion/", "lol:")
                
                # 3. Clean up Target (e.g., "http://.../Q100254962" -> "wd:Q100254962")
                if raw_target == "NOT_FOUND" or not raw_target:
                    target = "Unlinked"
                else:
                    target = raw_target.replace("http://www.wikidata.org/entity/", "wd:")
                    
                # 4. Parse Confidence as a float
                try:
                    confidence = float(raw_conf)
                except ValueError:
                    confidence = 0.0
                    
                # 5. Build the exact JSON dictionary React expects
                alignments.append({
                    "entity": source,
                    "wdTarget": target,
                    "confidence": confidence,
                    "label": raw_label.strip()
                })
                
        return alignments
    except Exception as e:
        print(f"Error reading alignments: {e}")
        return []

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)